# Generated by Django 5.1.3 on 2025-05-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VariantCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldensample.productfamily')),
            ],
        ),
        migrations.CreateModel(
            name='GoldenSampleCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=255)),
                ('variant_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldensample.variantcode')),
            ],
        ),
    ]
