# Generated by Django 5.1.3 on 2025-05-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFamily',
            new_name='GroupVariantCode',
        ),
        migrations.RenameField(
            model_name='variantcode',
            old_name='product_family',
            new_name='group',
        ),
        migrations.CreateModel(
            name='GoldenSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golden_code', models.CharField(max_length=255)),
                ('expire_date', models.DateField()),
                ('type_golden', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('calib', 'Calib')], max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldensample.variantcode')),
            ],
        ),
        migrations.DeleteModel(
            name='GoldenSampleCode',
        ),
    ]
