# Generated by Django 5.1.3 on 2025-05-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0002_rename_productfamily_groupvariantcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantcode',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CounterOnGolden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('golden_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goldensample.goldensample')),
            ],
        ),
    ]
