# Generated by Django 5.1.3 on 2025-05-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0003_variantcode_name_counterongolden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantcode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goldensample.groupvariantcode'),
        ),
    ]
