# Generated by Django 5.1.3 on 2025-05-28 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0004_alter_variantcode_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupvariantcode',
            name='last_time_tested',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
