# Generated by Django 5.1.3 on 2025-06-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0005_groupvariantcode_last_time_tested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupvariantcode',
            name='last_time_tested',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
