# Generated by Django 5.1.3 on 2025-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0006_alter_groupvariantcode_last_time_tested'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_input', models.CharField(max_length=255)),
                ('i_output', models.CharField(max_length=255)),
            ],
        ),
    ]
