# Generated by Django 5.1.3 on 2025-09-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0007_mapsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcbEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255)),
                ('result', models.BooleanField(blank=True, null=True)),
                ('time_date_tested', models.DateTimeField(auto_now_add=True)),
                ('shared_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goldensample.groupvariantcode')),
            ],
        ),
    ]
