# Generated by Django 5.1.3 on 2025-09-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0008_pcbevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcbevent',
            options={'ordering': ['-time_date_tested']},
        ),
        migrations.AlterField(
            model_name='pcbevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcb_events', to='goldensample.groupvariantcode'),
        ),
        migrations.AddIndex(
            model_name='pcbevent',
            index=models.Index(fields=['sn', 'time_date_tested'], name='goldensampl_sn_24814a_idx'),
        ),
        migrations.AddIndex(
            model_name='pcbevent',
            index=models.Index(fields=['shared_plate', 'result'], name='goldensampl_shared__f16e18_idx'),
        ),
    ]
