# Generated by Django 5.1.3 on 2025-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0010_clientname_codesmd_department_processname_timergroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersample',
            name='comennt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastersample',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
