# Generated by Django 5.1.3 on 2025-09-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0011_mastersample_comennt_mastersample_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typename',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mastersample',
            name='code_smd',
            field=models.ManyToManyField(blank=True, to='goldensample.codesmd'),
        ),
        migrations.AlterField(
            model_name='mastersample',
            name='master_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldensample.typename'),
        ),
    ]
