# Generated by Django 5.1.3 on 2025-09-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0012_department_color_typename_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersample',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goldensample.department'),
        ),
    ]
