# Generated by Django 5.1.3 on 2025-09-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0013_mastersample_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersample',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mastersample',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
