# Generated by Django 5.1.3 on 2025-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0014_alter_mastersample_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesmd',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
