# Generated by Django 5.1.3 on 2025-09-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0015_alter_codesmd_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endcode',
            name='master_sample',
        ),
        migrations.AddField(
            model_name='mastersample',
            name='endcodes',
            field=models.ManyToManyField(blank=True, to='goldensample.endcode'),
        ),
        migrations.AlterField(
            model_name='endcode',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
