# Generated by Django 5.1.3 on 2025-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0016_remove_endcode_master_sample_mastersample_endcodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineGoldensTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255, unique=True)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
