# Generated by Django 5.1.3 on 2025-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0017_machinegoldenstime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersample',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
