# Generated by Django 5.1.3 on 2025-11-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0018_mastersample_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterongolden',
            name='golden_sample',
        ),
        migrations.RemoveField(
            model_name='goldensample',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='pcbevent',
            name='group',
        ),
        migrations.RemoveField(
            model_name='variantcode',
            name='group',
        ),
        migrations.DeleteModel(
            name='MapSample',
        ),
        migrations.DeleteModel(
            name='CounterOnGolden',
        ),
        migrations.DeleteModel(
            name='GoldenSample',
        ),
        migrations.DeleteModel(
            name='PcbEvent',
        ),
        migrations.DeleteModel(
            name='GroupVariantCode',
        ),
        migrations.DeleteModel(
            name='VariantCode',
        ),
    ]
