# Generated by Django 5.1.3 on 2025-11-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0019_remove_counterongolden_golden_sample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndCodeTimeFWK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255)),
                ('site', models.PositiveIntegerField()),
                ('last_good_tested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LastResultFWK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255)),
                ('result', models.BooleanField(null=True)),
                ('date_time_tested', models.DateTimeField(auto_now_add=True)),
                ('machine_id', models.CharField(max_length=255)),
                ('site', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TempCheckMasterFWK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255)),
                ('site', models.PositiveIntegerField()),
                ('pass_res', models.BooleanField()),
                ('fail_res', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TempMasterShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255)),
                ('site', models.PositiveIntegerField()),
                ('if_set', models.BooleanField()),
                ('sn', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='typename',
            name='compute_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
