# Generated by Django 5.1.3 on 2025-11-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0020_endcodetimefwk_lastresultfwk_tempcheckmasterfwk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endcodetimefwk',
            name='last_good_tested',
        ),
        migrations.AddField(
            model_name='endcodetimefwk',
            name='last_good_tested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempmastershow',
            name='if_set',
            field=models.BooleanField(default=False),
        ),
    ]

