# Generated by Django 5.1.3 on 2025-11-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0022_alter_lastresultfwk_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcheckmasterfwk',
            name='pass_res',
            field=models.BooleanField(null=True),
        ),
    ]
