# Generated by Django 5.1.3 on 2025-11-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0023_alter_tempcheckmasterfwk_pass_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcheckmasterfwk',
            name='fail_res',
            field=models.BooleanField(null=True),
        ),
    ]
