# Generated by Django 5.1.3 on 2025-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0024_alter_tempcheckmasterfwk_fail_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersample',
            name='sn',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
