# Generated by Django 5.1.3 on 2025-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0025_alter_mastersample_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='endcodetimefwk',
            name='endcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
