# Generated by Django 5.1.3 on 2025-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0026_endcodetimefwk_endcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endcodetimefwk',
            name='site',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
