# Generated by Django 5.1.3 on 2026-01-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0027_alter_endcodetimefwk_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastersample',
            options={'permissions': [('can_update_create_goldens', 'Może dodawać i modyfikować wzorce')]},
        ),
    ]
