# Generated by Django 5.1.3 on 2026-01-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0028_alter_mastersample_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersample',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
