# Generated by Django 5.1.3 on 2026-04-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0029_mastersample_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSampleSubObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msn', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=1024)),
                ('mastersameple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subobjects', to='goldensample.mastersample')),
            ],
        ),
    ]
