# Generated by Django 5.1.3 on 2026-05-05 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldensample', '0030_mastersamplesubobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalNameProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mastersample',
            name='additional_project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goldensample.additionalnameproject'),
        ),
    ]
