# Generated by Django 5.1.3 on 2026-05-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullValidationMachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EndedCodesWithQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('queue', models.IntegerField()),
                ('full_validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='spea_service.fullvalidationmachinemodel')),
            ],
        ),
        migrations.AddField(
            model_name='fullvalidationmachinemodel',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spea_service.machine'),
        ),
    ]
