# Generated by Django 5.1.3 on 2026-05-22 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueTestValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_batch_id', models.UUIDField(default=uuid.uuid4)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fullvalidationmachinemodel',
            options={'ordering': ['-time_date']},
        ),
        migrations.RenameField(
            model_name='fullvalidationmachinemodel',
            old_name='date',
            new_name='time_date',
        ),
        migrations.CreateModel(
            name='GoldenTypeValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
                ('good_golden', models.BooleanField(default=False)),
                ('bad_golden', models.BooleanField(default=False)),
                ('validation_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spea_service.fullvalidationmachinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TestedSn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255)),
                ('bin', models.JSONField()),
                ('prev_phase', models.BooleanField()),
                ('test_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spea_service.uniquetestvalue')),
            ],
        ),
    ]
