# Generated by Django 5.1.3 on 2026-05-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0002_uniquetestvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvalidationmachinemodel',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goldentypevalidate',
            name='validation_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typesvalidate', to='spea_service.fullvalidationmachinemodel'),
        ),
    ]
