# Generated by Django 5.1.3 on 2026-05-22 16:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0003_fullvalidationmachinemodel_ended_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testedsn',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='fullvalidationmachinemodel',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='testedsn',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testedsn',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spea_service.machine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='testedsn',
            index=models.Index(fields=['machine', 'sn', '-date_time'], name='spea_servic_machine_e9ef0d_idx'),
        ),
    ]
