# Generated by Django 5.1.3 on 2026-05-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0004_alter_testedsn_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testedsn',
            name='test_num',
        ),
        migrations.DeleteModel(
            name='UniqueTestValue',
        ),
    ]
