# Generated by Django 5.1.3 on 2026-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0005_remove_testedsn_test_num_delete_uniquetestvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='testedsn',
            name='phase_error_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
