# Generated by Django 5.1.3 on 2026-05-27 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0006_testedsn_phase_error_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('prev_done', models.BooleanField(default=False)),
                ('bins_done', models.BooleanField(default=False)),
            ],
        ),
    ]
