# Generated by Django 5.1.3 on 2026-06-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0007_tasknum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForceValidMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField(auto_now_add=True)),
                ('date_time_end', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_time_start'],
            },
        ),
        migrations.AlterField(
            model_name='fullvalidationmachinemodel',
            name='time_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fullvalidationmachinemodel',
            index=models.Index(fields=['machine', 'is_valid'], name='full_valid_mach_idx'),
        ),
        migrations.AddField(
            model_name='forcevalidmachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spea_service.machine'),
        ),
        migrations.AddIndex(
            model_name='forcevalidmachine',
            index=models.Index(fields=['machine', 'is_valid'], name='force_valid_mach_idx'),
        ),
    ]
