# Generated by Django 5.1.3 on 2026-06-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0008_forcevalidmachine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcevalidmachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forcevalidation', to='spea_service.machine'),
        ),
    ]
