# Generated by Django 5.1.3 on 2026-07-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0009_alter_forcevalidmachine_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='testedsn',
            name='phase_error_num_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
