# Generated by Django 5.1.3 on 2026-07-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0010_testedsn_phase_error_num_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullvalidationmachinemodel',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullvalidation', to='spea_service.machine'),
        ),
    ]
