# Generated by Django 5.1.3 on 2026-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0011_alter_fullvalidationmachinemodel_machine'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fullvalidationmachinemodel',
            index=models.Index(fields=['machine', 'is_valid', '-time_date'], name='full_valid_mach_time_idx'),
        ),
    ]
