# Generated by Django 5.1.3 on 2026-08-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0012_fullvalidationmachinemodel_full_valid_mach_time_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Podajemy dział osobę do której należy to hasło', max_length=255)),
                ('password', models.CharField(help_text='Hasło, nie musi byc hashowane bo to wewnetrzny system', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValidPasswordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateTimeField(auto_now_add=True)),
                ('valid_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spea_service.validpassword')),
            ],
        ),
    ]
