# Generated by Django 5.1.3 on 2026-09-17 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_service', '0013_validpassword_validpasswordlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknum',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
