GET http://127.0.0.1:8000/api/process/1/a1fdaa43-fc91-45f8-a04e-d76f5495c584/product-objects/?page=2&place_isnull=false


###

POST http://10.140.113.33/api/add-to-counter/
Content-Type: application/json

{
  "name": "DAIMLER PCB 3 to precise data",
  "machine_id": "AA123",
  "serial_number": "16223028401A21419319"
}