# Generated by Django 5.1.3 on 2026-03-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessUnlinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('SC', 'Success'), ('ER', 'Error'), ('UN', 'Unknown')], default='UN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserUnlinkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_card', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessUnlinkingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('phases', models.CharField(choices=[('DL', 'Deleting'), ('101', 'Setting 101')], max_length=1024)),
                ('error_code', models.CharField(blank=True, max_length=255, null=True)),
                ('process_unlinking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processdata', to='unlinker.processunlinking')),
            ],
        ),
        migrations.AddField(
            model_name='processunlinking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processunlinkings', to='unlinker.userunlinkerprofile'),
        ),
    ]
