# Generated by Django 5.1.3 on 2026-03-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlinker', '0002_alter_userunlinkerprofile_user_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userunlinkerprofile',
            name='user_card',
            field=models.CharField(max_length=10),
        ),
    ]
