# Generated by Django 5.1.3 on 2026-03-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlinker', '0003_alter_userunlinkerprofile_user_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='processunlinkingdata',
            name='process_type',
            field=models.CharField(blank=True, choices=[('DL', 'Deleting'), ('101', 'Setting 101')], max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='processunlinkingdata',
            name='phases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
