# Generated by Django 5.1.3 on 2026-03-20 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlinker', '0004_processunlinkingdata_process_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processunlinking',
            name='time_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
