# Generated by Django 5.1.3 on 2026-04-22 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlinker', '0005_processunlinking_time_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processunlinking',
            options={'permissions': [('can_unlinking', 'Can unlink products')]},
        ),
        migrations.RemoveField(
            model_name='processunlinking',
            name='user',
        ),
        migrations.AddField(
            model_name='processunlinking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
