# Generated by Django 5.1.3 on 2026-04-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlinker', '0006_alter_processunlinking_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processunlinking',
            old_name='created_by',
            new_name='user',
        ),
    ]
