# Generated by Django 5.1.3 on 2026-04-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlinker', '0007_rename_created_by_processunlinking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processunlinking',
            old_name='user',
            new_name='created_by',
        ),
    ]
