# Generated by Django 5.1.3 on 2026-08-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestedParrotSn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateTimeField()),
                ('done', models.BooleanField()),
                ('error', models.TextField(blank=True, null=True)),
                ('internal_code', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'id', 'sn'], name='parrot_date_id_sn_idx'), models.Index(fields=['date', 'done', 'internal_code'], name='parrot_date_done_ic_idx')],
            },
        ),
    ]
