# Generated by Django 5.1.3 on 2026-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testedparrotsn',
            name='sn',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
