# Generated by Django 5.1.3 on 2026-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrot', '0002_alter_testedparrotsn_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='testedparrotsn',
            name='certyficate',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='testedparrotsn',
            index=models.Index(fields=['certyficate', 'done'], name='parrot_cert_done_idx'),
        ),
    ]
