# Generated by Django 5.1.3 on 2026-01-30 14:33

import django.core.validators
import django.db.models.deletion
import spea_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSpea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speacard', to='spea_control.locationspea')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=spea_control.models.upload_to_uuid, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt']), spea_control.models.validate_is_pure_text])),
                ('active', models.BooleanField(default=False)),
                ('spea_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spea_control.speacard')),
            ],
        ),
    ]
