# Generated by Django 5.1.3 on 2026-01-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speacard',
            name='sn',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
