# Generated by Django 5.1.3 on 2026-01-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0002_alter_speacard_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speacard',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speacard', to='spea_control.locationspea'),
        ),
    ]
