# Generated by Django 5.1.3 on 2026-01-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0003_alter_speacard_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='speacard',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
