# Generated by Django 5.1.3 on 2026-01-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0004_speacard_is_broken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisfile',
            name='spea_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='spea_control.speacard'),
        ),
    ]
