# Generated by Django 5.1.3 on 2026-01-31 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0005_alter_diagnosisfile_spea_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
