# Generated by Django 5.1.3 on 2026-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0006_diagnosisfile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='speacard',
            name='out_of_company',
            field=models.BooleanField(default=False),
        ),
    ]
