# Generated by Django 5.1.3 on 2026-02-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0007_speacard_out_of_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speacard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='speacard',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speacard',
            name='is_broken',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='speacard',
            name='out_of_company',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='diagnosisfile',
            index=models.Index(fields=['spea_card', '-created_at'], name='spea_contro_spea_ca_9397e5_idx'),
        ),
    ]
