# Generated by Django 5.1.3 on 2026-02-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0008_alter_speacard_options_alter_speacard_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveLogSpea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spea_control.speacard')),
            ],
        ),
    ]
