# Generated by Django 5.1.3 on 2026-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spea_control', '0009_movelogspea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movelogspea',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movelogspea',
            name='movement_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
