# Generated by Django 5.1.3 on 2026-09-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalletFullInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_board_id', models.IntegerField()),
                ('pallet_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('full_used', False)), fields=['pallet_number'], name='idx_active_pallet_num')],
                'constraints': [models.UniqueConstraint(fields=('db_board_id', 'pallet_number'), name='unique_board_pallet')],
            },
        ),
        migrations.CreateModel(
            name='SnToBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=255)),
                ('place_num', models.IntegerField()),
                ('aoi_result', models.BooleanField(blank=True, null=True)),
                ('ict_result', models.BooleanField(blank=True, null=True)),
                ('fvt_result', models.BooleanField(blank=True, null=True)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sn_boards', to='aidon.palletfullinfo')),
            ],
            options={
                'indexes': [models.Index(fields=['pallet', 'place_num'], name='idx_sn_pallet_place')],
                'constraints': [models.UniqueConstraint(fields=('pallet', 'place_num'), name='unique_pallet_place')],
            },
        ),
    ]
