# Generated by Django 5.1.3 on 2026-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidon', '0002_sntoboard_full_result'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='palletfullinfo',
            name='unique_board_pallet',
        ),
        migrations.AddField(
            model_name='palletfullinfo',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='palletfullinfo',
            index=models.Index(fields=['product', 'db_board_id'], name='idx_product_db_board_id'),
        ),
        migrations.AddConstraint(
            model_name='palletfullinfo',
            constraint=models.UniqueConstraint(fields=('product', 'db_board_id', 'pallet_number'), name='unique_product_board_pallet'),
        ),
    ]
