# Generated by Django 5.1.3 on 2026-06-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version_of_collectors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorsServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorComputerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching_path', models.CharField(max_length=255)),
                ('folder_in_server_name', models.CharField(max_length=255)),
                ('slow_mode', models.BooleanField(default=False)),
                ('collector_computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollector.collectorcomputer')),
            ],
        ),
        migrations.CreateModel(
            name='CollectorRuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=255)),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('copy_file_force', models.BooleanField(default=False)),
                ('collector_computer_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollector.collectorcomputersettings')),
            ],
        ),
    ]
