# Generated by Django 5.1.3 on 2026-06-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0002_collectorcomputer_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorsservers',
            name='basic_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
