# Generated by Django 5.1.3 on 2026-06-17 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_form', models.IntegerField()),
                ('counter', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(200))),
                ('last_clear_time', models.DateTimeField(auto_now=True)),
                ('who', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordToUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passw', models.CharField(max_length=255)),
                ('who', models.CharField(max_length=255)),
            ],
        ),
    ]
