# Generated by Django 5.1.3 on 2026-06-17 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmachine',
            name='counter',
            field=models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(200)),
        ),
        migrations.AlterField(
            model_name='checkmachine',
            name='who',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
