# Generated by Django 5.1.3 on 2026-06-17 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0002_alter_checkmachine_counter_alter_checkmachine_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmachine',
            name='counter',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Counter'),
        ),
    ]
