# Generated by Django 5.1.3 on 2026-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0003_alter_checkmachine_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_id', models.IntegerField()),
                ('intenal_code', models.IntegerField()),
                ('who', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='checkmachine',
            old_name='assembly_form',
            new_name='phase_id',
        ),
        migrations.RemoveField(
            model_name='checkmachine',
            name='last_clear_time',
        ),
        migrations.RemoveField(
            model_name='checkmachine',
            name='who',
        ),
    ]
