# Generated by Django 5.1.3 on 2026-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0004_unlockhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmachine',
            name='phase_id',
            field=models.IntegerField(unique=True),
        ),
    ]
