# Generated by Django 5.1.3 on 2026-06-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0005_alter_checkmachine_phase_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlockhistory',
            old_name='intenal_code',
            new_name='internal_code',
        ),
    ]
