# Generated by Django 5.1.3 on 2024-12-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_counterfromlastbackup_time_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterfromlastbackup',
            name='time_date',
        ),
    ]
