# Generated by Django 5.1.3 on 2025-03-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_counterfromlastbackup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='countersumfromlastmaint',
            old_name='summ',
            new_name='counter',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='counter_summ',
            new_name='counter_last_maint',
        ),
        migrations.AddField(
            model_name='fixture',
            name='counter_all',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fullcounter'),
        ),
    ]
