# Generated by Django 5.1.3 on 2025-03-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_counterhistory_delete_counterfromlastbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='cycles_limit',
            field=models.IntegerField(default=50000),
        ),
    ]
