# Generated by Django 5.1.3 on 2025-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_fixture_cycles_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255)),
                ('machine_name', models.CharField(max_length=255)),
            ],
        ),
    ]
