# Generated by Django 5.1.3 on 2025-06-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MachineCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_variant', models.CharField(blank=True, max_length=255, null=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.machine')),
            ],
        ),
    ]
