# Generated by Django 5.1.3 on 2025-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_machine_machine_id_machinecondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
