# Generated by Django 5.1.3 on 2026-05-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_fixture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinecondition',
            name='machine',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='MachineCondition',
        ),
    ]
