# Generated by Django 5.1.3 on 2026-06-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('plant', models.CharField(max_length=255)),
                ('version', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('test_station_name', models.CharField(max_length=255)),
                ('s_type', models.CharField(choices=[('ICT', 'ict'), ('FVT', 'fvt')], max_length=255)),
                ('test_station_id', models.CharField(max_length=255)),
                ('machine_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_collector.basesettings')),
            ],
        ),
        migrations.CreateModel(
            name='StationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(max_length=255)),
                ('production_serial', models.CharField(max_length=255)),
                ('decoded_serial', models.CharField(max_length=255)),
                ('devicetype', models.CharField(max_length=255)),
                ('hw_version', models.CharField(max_length=255)),
                ('bootloader_version', models.CharField(max_length=255)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='special_collector.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('look_what', models.CharField(max_length=255)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='special_collector.station')),
            ],
        ),
    ]
