# Generated by Django 5.1.3 on 2026-06-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0002_product_is_active_stationheader_line_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationHeader',
        ),
    ]
