# Generated by Django 5.1.3 on 2026-06-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0003_delete_stationheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='test_station_id',
        ),
    ]
