# Generated by Django 5.1.3 on 2026-06-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0004_remove_station_test_station_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='machine_id',
        ),
    ]
