# Generated by Django 5.1.3 on 2026-06-30 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0005_remove_station_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='special_collector.product'),
        ),
    ]
