# Generated by Django 5.1.3 on 2026-06-30 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0006_station_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_collector.product'),
        ),
    ]
