# Generated by Django 5.1.3 on 2026-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0007_alter_station_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationstage',
            old_name='look_what',
            new_name='pattern_1',
        ),
        migrations.AddField(
            model_name='stationstage',
            name='pattern_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stationstage',
            name='pattern_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
