# Generated by Django 5.1.3 on 2026-06-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0008_rename_look_what_stationstage_pattern_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='line_splitter',
            field=models.CharField(default=';', max_length=1),
        ),
        migrations.AlterField(
            model_name='stationstage',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_collector.station'),
        ),
    ]
