# Generated by Django 5.1.3 on 2026-07-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0009_station_line_splitter_alter_stationstage_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=255)),
                ('partnumber', models.CharField(max_length=255)),
                ('decoded_serial', models.CharField(max_length=255)),
                ('devicetype', models.CharField(max_length=255)),
                ('hw_version', models.CharField(max_length=255)),
                ('bootloader_version', models.CharField(max_length=255)),
            ],
        ),
    ]
