# Generated by Django 5.1.3 on 2026-07-06 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0011_alter_headerdata_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderDataStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=255, unique=True)),
                ('partnumber', models.CharField(max_length=255)),
                ('decoded_serial', models.CharField(max_length=255)),
                ('devicetype', models.CharField(max_length=255)),
                ('hw_version', models.CharField(max_length=255)),
                ('bootloader_version', models.CharField(max_length=255)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='special_collector.station')),
            ],
        ),
        migrations.DeleteModel(
            name='HeaderData',
        ),
    ]
