# Generated by Django 5.1.3 on 2026-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0012_headerdatastation_delete_headerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerdatastation',
            name='bootloader_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headerdatastation',
            name='decoded_serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headerdatastation',
            name='devicetype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headerdatastation',
            name='hw_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headerdatastation',
            name='partnumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headerdatastation',
            name='sn',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
