# Generated by Django 5.1.3 on 2026-07-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0013_alter_headerdatastation_bootloader_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='queue',
            field=models.IntegerField(null=True),
        ),
    ]
