# Generated by Django 5.1.3 on 2026-07-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0014_station_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerdatastation',
            name='mac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
