# Generated by Django 5.1.3 on 2026-07-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collector', '0015_headerdatastation_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
