# Generated by Django 5.1.3 on 2025-08-05 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOneMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_input', models.CharField(max_length=255)),
                ('s_output', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('only_one_product_object', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mother', models.BooleanField(default=False)),
                ('serial_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('full_sn', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateField(blank=True, default=None, null=True)),
                ('production_date', models.DateField(blank=True, default=None, null=True)),
                ('exp_date_in_process', models.DateField(blank=True, default=None, null=True)),
                ('quranteen_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('ex_mother', models.CharField(blank=True, max_length=255, null=True)),
                ('end', models.BooleanField(default=False)),
                ('current_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.place')),
                ('mother_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_object', to='checkprocess.productobject')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_objects', to='checkprocess.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('pos_x', models.FloatField(blank=True, default=0.0, null=True)),
                ('pos_y', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='checkprocess.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductObjectProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('who_entry', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('who_exit', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_logs', to='checkprocess.place')),
                ('product_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='checkprocess.productobject')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productprocess')),
            ],
        ),
        migrations.AddField(
            model_name='productobject',
            name='current_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.productprocess'),
        ),
        migrations.AddField(
            model_name='place',
            name='process',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_place', to='checkprocess.productprocess'),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('target_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(default='default', max_length=50)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('animated', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='checkprocess.productprocess')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='AppToKill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killing_flag', models.BooleanField(default=False)),
                ('line_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.place')),
                ('process', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcessCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_fail', models.BooleanField(default=True)),
                ('product_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcessDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_days_exp_date', models.IntegerField(blank=True, default=None, null=True)),
                ('quranteen_time', models.IntegerField(blank=True, default=None, null=True)),
                ('respect_quranteen_time', models.BooleanField(default=False)),
                ('expecting_child', models.BooleanField(default=False)),
                ('killing_app', models.BooleanField(default=False)),
                ('production_process_type', models.BooleanField(default=False)),
                ('check_outside_database', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('product_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcessEnding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endings', to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcessStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_days_exp_date', models.IntegerField(blank=True, default=None, null=True)),
                ('quranteen_time', models.IntegerField(blank=True, default=None, null=True)),
                ('respect_quranteen_time', models.BooleanField(default=False)),
                ('expecting_child', models.BooleanField(default=False)),
                ('killing_app', models.BooleanField(default=False)),
                ('add_multi', models.BooleanField(default=False)),
                ('product_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('child_limit', models.IntegerField(blank=True, default=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproduct', to='checkprocess.product')),
            ],
        ),
        migrations.AddField(
            model_name='productobject',
            name='sub_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_objects', to='checkprocess.subproduct'),
        ),
        migrations.CreateModel(
            name='LastProductOnPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.place')),
                ('product_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productprocess')),
                ('p_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductObjectProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_processes', to='checkprocess.productobject')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_processes', to='checkprocess.productprocess')),
            ],
            options={
                'unique_together': {('product_object', 'process')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'process')},
        ),
    ]
