# Generated by Django 5.1.3 on 2025-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprocess',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
