# Generated by Django 5.1.3 on 2025-06-10 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='checkprocess.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductObjectProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productprocess')),
                ('product_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_processes', to='checkprocess.productobject')),
            ],
            options={
                'unique_together': {('product_object', 'process')},
            },
        ),
        migrations.CreateModel(
            name='ProductObjectProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('who_entry', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('who_exit', models.CharField(blank=True, max_length=255, null=True)),
                ('product_object_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='checkprocess.productobjectprocess')),
            ],
        ),
    ]
