# Generated by Django 5.1.3 on 2025-08-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0002_alter_productprocess_pos_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='cond_path',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConditionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField(default=False)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productprocess')),
            ],
            options={
                'ordering': ['-time_date'],
            },
        ),
    ]
