# Generated by Django 5.1.3 on 2025-06-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0003_alter_productobject_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobject',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_objects', to='checkprocess.product'),
        ),
    ]
