# Generated by Django 5.1.3 on 2025-08-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0003_productprocess_cond_path_conditionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productobject'),
        ),
    ]
