# Generated by Django 5.1.3 on 2025-06-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0004_alter_productobject_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobjectprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_processes', to='checkprocess.productprocess'),
        ),
    ]
