# Generated by Django 5.1.3 on 2025-08-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0004_conditionlog_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionlog',
            name='who',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
