# Generated by Django 5.1.3 on 2025-06-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0005_alter_productobjectprocess_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='expire_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
