# Generated by Django 5.1.3 on 2025-08-25 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0005_conditionlog_who'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceGroupToAppKill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='checkprocess.placegrouptoappkill'),
        ),
    ]
