# Generated by Django 5.1.3 on 2025-08-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0006_placegrouptoappkill_place_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placegrouptoappkill',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
