# Generated by Django 5.1.3 on 2025-06-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0007_place_productobject_mother_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='process',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_place', to='checkprocess.productprocess'),
        ),
    ]
