# Generated by Django 5.1.3 on 2025-08-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0007_alter_placegrouptoappkill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprocessdefault',
            name='killing_app',
        ),
        migrations.RemoveField(
            model_name='productprocessstart',
            name='killing_app',
        ),
        migrations.AddField(
            model_name='productprocess',
            name='killing_app',
            field=models.BooleanField(default=False),
        ),
    ]
