# Generated by Django 5.1.3 on 2025-08-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0008_remove_productprocessdefault_killing_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptokill',
            name='process',
        ),
    ]
