# Generated by Django 5.1.3 on 2025-06-14 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0008_place_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='current_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.place'),
        ),
        migrations.AddField(
            model_name='productobject',
            name='current_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.productprocess'),
        ),
    ]
