# Generated by Django 5.1.3 on 2025-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0009_remove_apptokill_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='respect_fifo_rules',
            field=models.BooleanField(default=True),
        ),
    ]
