# Generated by Django 5.1.3 on 2025-06-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0009_productobject_current_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='exp_date_in_process',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productobject',
            name='full_sn',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productobject',
            name='production_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
