# Generated by Django 5.1.3 on 2025-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0010_productprocess_respect_fifo_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobject',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
