# Generated by Django 5.1.3 on 2025-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0010_productobject_exp_date_in_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobjectprocess',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='can_multi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='changing_exp_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='how_much_days_exp_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='quranteen_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
