# Generated by Django 5.1.3 on 2025-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0011_productobjectprocess_is_end_productprocess_can_multi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='quranteen_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
