# Generated by Django 5.1.3 on 2025-09-11 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0011_alter_productobject_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='placegrouptoappkill',
            name='last_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
