# Generated by Django 5.1.3 on 2025-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0012_productobject_quranteen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='respect_quranteen_time',
            field=models.BooleanField(default=False),
        ),
    ]
