# Generated by Django 5.1.3 on 2025-09-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0012_placegrouptoappkill_last_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placegrouptoappkill',
            options={'ordering': ['name']},
        ),
    ]
