# Generated by Django 5.1.3 on 2025-09-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0013_alter_placegrouptoappkill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='set_not_full',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productobject',
            name='is_full',
            field=models.BooleanField(default=True),
        ),
    ]
