# Generated by Django 5.1.3 on 2025-09-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0014_edge_set_not_full_productobject_is_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='set_not_full',
        ),
        migrations.CreateModel(
            name='EdgeOptionsSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_not_full', models.BooleanField(default=True)),
                ('check_same_out_same_in', models.BooleanField(default=False)),
                ('edge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edgeoptions', to='checkprocess.edge')),
            ],
        ),
    ]
