# Generated by Django 5.1.3 on 2025-06-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0014_productobject_is_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='expecting_child',
            field=models.BooleanField(default=False),
        ),
    ]
