# Generated by Django 5.1.3 on 2025-06-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0015_productprocess_expecting_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='ex_mother',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
