# Generated by Django 5.1.3 on 2025-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0015_remove_edge_set_not_full_edgeoptionssets'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='show_the_couter',
            field=models.BooleanField(default=False),
        ),
    ]
