# Generated by Django 5.1.3 on 2025-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0016_productprocessdefault_show_the_couter'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='validate_fish',
            field=models.BooleanField(default=False),
        ),
    ]
