# Generated by Django 5.1.3 on 2025-06-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0016_productobject_ex_mother'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppToKill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killing_flag', models.BooleanField(default=False)),
                ('line_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.place')),
            ],
        ),
    ]
