# Generated by Django 5.1.3 on 2025-06-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0017_apptokill'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='killing_app',
            field=models.BooleanField(default=False),
        ),
    ]
