# Generated by Django 5.1.3 on 2025-09-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0017_productprocess_validate_fish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprocess',
            name='validate_fish',
        ),
        migrations.AddField(
            model_name='productprocessdefault',
            name='validate_fish',
            field=models.BooleanField(default=False),
        ),
    ]
