# Generated by Django 5.1.3 on 2025-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0018_productprocess_killing_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='only_one_product_object',
            field=models.BooleanField(default=False),
        ),
    ]
