# Generated by Django 5.1.3 on 2025-09-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0018_remove_productprocess_validate_fish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='use_list_endpoint',
            field=models.BooleanField(default=False),
        ),
    ]
