# Generated by Django 5.1.3 on 2025-06-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0019_place_only_one_product_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productobjectprocess',
            name='is_end',
        ),
        migrations.AddField(
            model_name='productobject',
            name='end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='ending_process',
            field=models.BooleanField(default=False),
        ),
    ]
