# Generated by Django 5.1.3 on 2025-10-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0019_productprocessdefault_use_list_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobjectprocesslog',
            name='movement_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
