# Generated by Django 5.1.3 on 2025-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0020_productobjectprocesslog_movement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBasesSpiMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_base_name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('identyficator', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
