# Generated by Django 5.1.3 on 2025-06-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0020_remove_productobjectprocess_is_end_productobject_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='re_use',
            field=models.BooleanField(default=False),
        ),
    ]
