# Generated by Django 5.1.3 on 2025-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0021_productobject_re_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='child_limit',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
