# Generated by Django 5.1.3 on 2025-11-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0021_databasesspimap'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFromSpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_id', models.IntegerField()),
                ('pcb_name', models.CharField(max_length=255)),
                ('time_date', models.DateTimeField()),
                ('machine_name', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
    ]
