# Generated by Django 5.1.3 on 2025-07-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0022_product_child_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackMapProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_map_back', to='checkprocess.productprocess')),
                ('front', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_map_front', to='checkprocess.productprocess')),
            ],
        ),
    ]
