# Generated by Django 5.1.3 on 2025-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0022_logfromspi'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobjectprocesslog',
            name='name_of_productig_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
