# Generated by Django 5.1.3 on 2025-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0023_productobjectprocesslog_name_of_productig_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastproductonplace',
            name='name_of_productig_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
