# Generated by Django 5.1.3 on 2025-07-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0024_remove_productobject_re_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parser_type',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
