# Generated by Django 5.1.3 on 2025-11-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0024_lastproductonplace_name_of_productig_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasesspimap',
            name='line_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.place'),
        ),
        migrations.AlterField(
            model_name='logfromspi',
            name='machine_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.place'),
        ),
    ]
