# Generated by Django 5.1.3 on 2025-11-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0025_alter_databasesspimap_line_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productobject',
            index=models.Index(fields=['current_place', 'end'], name='idx_place_end'),
        ),
    ]
