# Generated by Django 5.1.3 on 2025-07-11 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0025_product_parser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='child_limit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parser_type',
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animated', models.BooleanField(default=False)),
                ('edge_type', models.CharField(default='smoothstep', max_length=50)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_form', to='checkprocess.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='checkprocess.node')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_limit', models.IntegerField(blank=True, default=20, null=True)),
                ('parser_type', models.CharField(default='default', max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.product')),
            ],
        ),
    ]
