# Generated by Django 5.1.3 on 2025-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0026_node_remove_product_child_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
