# Generated by Django 5.1.3 on 2025-11-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0026_productobject_idx_place_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='use_poke',
            field=models.BooleanField(default=False),
        ),
    ]
