# Generated by Django 5.1.3 on 2025-07-15 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0027_subproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='checkprocess.productprocess'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='checkprocess.productprocess'),
        ),
        migrations.AlterModelOptions(
            name='productprocess',
            options={},
        ),
        migrations.RenameField(
            model_name='productprocess',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='edge_type',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='changing_exp_date',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='ending_process',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='expecting_child',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='how_much_days_exp_date',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='killing_app',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='quranteen_time',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='respect_quranteen_time',
        ),
        migrations.AddField(
            model_name='edge',
            name='type',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='pos_x',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprocess',
            name='pos_y',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprocess',
            name='type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproduct', to='checkprocess.product'),
        ),
        migrations.CreateModel(
            name='ProductProcessCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_fail', models.BooleanField()),
                ('product_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcessDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_days_exp_date', models.IntegerField(blank=True, default=None, null=True)),
                ('quranteen_time', models.IntegerField(blank=True, default=None, null=True)),
                ('respect_quranteen_time', models.BooleanField(default=False)),
                ('expecting_child', models.BooleanField(default=False)),
                ('killing_app', models.BooleanField(default=False)),
                ('product_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcessEnding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endings', to='checkprocess.productprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcessStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_days_exp_date', models.IntegerField(blank=True, default=None, null=True)),
                ('quranteen_time', models.IntegerField(blank=True, default=None, null=True)),
                ('respect_quranteen_time', models.BooleanField(default=False)),
                ('expecting_child', models.BooleanField(default=False)),
                ('killing_app', models.BooleanField(default=False)),
                ('product_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='checkprocess.productprocess')),
            ],
        ),
        migrations.DeleteModel(
            name='BackMapProcess',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
