# Generated by Django 5.1.3 on 2025-11-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0027_productprocessdefault_use_poke'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='sito_cycle_limit',
            field=models.PositiveIntegerField(default=300000),
        ),
        migrations.AddField(
            model_name='productobject',
            name='sito_cycles_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logfromspi',
            name='time_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
