# Generated by Django 5.1.3 on 2025-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0028_productobject_sito_cycle_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobject',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
