# Generated by Django 5.1.3 on 2025-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0028_alter_edge_source_alter_edge_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprocesscondition',
            name='pass_fail',
            field=models.BooleanField(default=True),
        ),
    ]
