# Generated by Django 5.1.3 on 2025-11-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0029_alter_productobject_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='working_only_if_obj_on_machine',
            field=models.BooleanField(default=False),
        ),
    ]
