# Generated by Django 5.1.3 on 2025-07-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0029_alter_productprocesscondition_pass_fail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
