# Generated by Django 5.1.3 on 2025-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0030_alter_edge_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='source_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='target_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
