# Generated by Django 5.1.3 on 2025-11-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0030_productprocessdefault_working_only_if_obj_on_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='max_in_process',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
