# Generated by Django 5.1.3 on 2025-07-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0031_edge_source_handle_edge_target_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='parser_type',
        ),
    ]
