# Generated by Django 5.1.3 on 2025-11-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0031_productobject_max_in_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='how_much_hours_max_working',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
