# Generated by Django 5.1.3 on 2025-07-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0032_remove_subproduct_parser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='sub_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_objects', to='checkprocess.subproduct'),
        ),
    ]
