# Generated by Django 5.1.3 on 2025-11-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0032_productprocessdefault_how_much_hours_max_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('shown_app', models.BooleanField(default=False)),
                ('show_server', models.BooleanField(default=False)),
                ('time_date_shown_app', models.DateTimeField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.place')),
            ],
        ),
    ]
