# Generated by Django 5.1.3 on 2025-07-24 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0033_productobject_sub_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productobjectprocesslog',
            name='product_object_process',
        ),
        migrations.AddField(
            model_name='productobjectprocesslog',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productprocess'),
        ),
        migrations.AddField(
            model_name='productobjectprocesslog',
            name='product_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='checkprocess.productobject'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'process')},
        ),
    ]
