# Generated by Django 5.1.3 on 2025-11-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0033_messagetoapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetoapp',
            old_name='show_server',
            new_name='send',
        ),
        migrations.RenameField(
            model_name='messagetoapp',
            old_name='time_date_shown_app',
            new_name='when_trigger',
        ),
        migrations.RemoveField(
            model_name='messagetoapp',
            name='shown_app',
        ),
    ]
