# Generated by Django 5.1.3 on 2025-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0034_rename_show_server_messagetoapp_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='stencil_production_process_type',
            field=models.BooleanField(default=False),
        ),
    ]
