# Generated by Django 5.1.3 on 2025-07-28 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0034_remove_productobjectprocesslog_product_object_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprocesscondition',
            name='product_process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='checkprocess.productprocess'),
        ),
        migrations.AlterField(
            model_name='productprocessdefault',
            name='product_process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='checkprocess.productprocess'),
        ),
        migrations.AlterField(
            model_name='productprocessending',
            name='product_process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endings', to='checkprocess.productprocess'),
        ),
        migrations.AlterField(
            model_name='productprocessstart',
            name='product_process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='checkprocess.productprocess'),
        ),
    ]
