# Generated by Django 5.1.3 on 2025-11-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0035_productprocessdefault_stencil_production_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetoapp',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.product'),
        ),
    ]
