# Generated by Django 5.1.3 on 2025-07-28 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0035_alter_productprocesscondition_product_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptokill',
            name='process',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productprocess'),
        ),
        migrations.AlterField(
            model_name='apptokill',
            name='line_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.place'),
        ),
    ]
