# Generated by Django 5.1.3 on 2025-11-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0036_messagetoapp_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProcessFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.BooleanField(default=False)),
                ('mother_object', models.BooleanField(default=False)),
                ('sub_product', models.BooleanField(default=False)),
                ('is_mother', models.BooleanField(default=False)),
                ('current_process', models.BooleanField(default=False)),
                ('current_place', models.BooleanField(default=False)),
                ('serial_number', models.BooleanField(default=False)),
                ('full_sn', models.BooleanField(default=False)),
                ('created_at', models.BooleanField(default=False)),
                ('expire_date', models.BooleanField(default=False)),
                ('production_date', models.BooleanField(default=False)),
                ('exp_date_in_process', models.BooleanField(default=False)),
                ('quranteen_time', models.BooleanField(default=False)),
                ('max_in_process', models.BooleanField(default=False)),
                ('ex_mother', models.BooleanField(default=False)),
                ('sito_cycle_limit', models.BooleanField(default=False)),
                ('sito_cycles_count', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
                ('is_full', models.BooleanField(default=False)),
                ('product_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='checkprocess.productprocess')),
            ],
        ),
    ]
