# Generated by Django 5.1.3 on 2025-07-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0036_apptokill_process_alter_apptokill_line_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='production_process_type',
            field=models.BooleanField(default=False),
        ),
    ]
