# Generated by Django 5.1.3 on 2025-07-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0037_productprocessdefault_production_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessstart',
            name='add_multi',
            field=models.BooleanField(default=False),
        ),
    ]
