# Generated by Django 5.1.3 on 2025-11-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0037_productprocessfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBasesASMMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_base_name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('identyficator', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('line_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.place')),
            ],
        ),
    ]
