# Generated by Django 5.1.3 on 2025-08-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0038_productprocessstart_add_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='check_outside_database',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
