# Generated by Django 5.1.3 on 2025-11-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0038_databasesasmmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='last_move',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
