# Generated by Django 5.1.3 on 2025-08-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0039_productprocessdefault_check_outside_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOneMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_input', models.CharField(max_length=255)),
                ('s_output', models.CharField(max_length=255)),
            ],
        ),
    ]
