# Generated by Django 5.1.3 on 2025-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0039_productobject_last_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessfields',
            name='last_move',
            field=models.BooleanField(default=False),
        ),
    ]
