# Generated by Django 5.1.3 on 2025-08-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0040_onetoonemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProductOnPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('p_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkprocess.subproduct')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.place')),
                ('product_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productprocess')),
            ],
        ),
    ]
