# Generated by Django 5.1.3 on 2025-11-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0040_productprocessfields_last_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='free_plain_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productobject',
            name='sito_basic_unnamed_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
