# Generated by Django 5.1.3 on 2025-11-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0041_productobject_free_plain_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessfields',
            name='free_plain_text',
            field=models.BooleanField(default=False),
        ),
    ]
