# Generated by Django 5.1.3 on 2025-11-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0042_productprocessfields_free_plain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessfields',
            name='sito_basic_unnamed_place',
            field=models.BooleanField(default=False),
        ),
    ]
