# Generated by Django 5.1.3 on 2025-11-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0043_productprocessfields_sito_basic_unnamed_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='search',
            field=models.BooleanField(default=False),
        ),
    ]
