# Generated by Django 5.1.3 on 2025-12-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0044_productprocess_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='placegrouptoappkill',
            name='checking',
            field=models.BooleanField(default=True),
        ),
    ]
