# Generated by Django 5.1.3 on 2025-12-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0045_placegrouptoappkill_checking'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessdefault',
            name='quranteen_time_receive',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
