# Generated by Django 5.1.3 on 2025-12-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0046_productprocessdefault_quranteen_time_receive'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFromMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_uuid_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('place_name_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('product_sn', models.CharField(max_length=255)),
                ('who', models.CharField(max_length=255, null=True)),
                ('error_message', models.TextField()),
                ('error_code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.place')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.productprocess')),
            ],
        ),
    ]
