# Generated by Django 5.1.3 on 2025-12-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0047_logfrommistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfrommistake',
            name='movement_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logfrommistake',
            name='error_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logfrommistake',
            name='place_name_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logfrommistake',
            name='process_uuid_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
