# Generated by Django 5.1.3 on 2025-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0048_logfrommistake_movement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfrommistake',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
