# Generated by Django 5.1.3 on 2025-12-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0049_logfrommistake_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productobjectprocesslog',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='productobjectprocesslog',
            name='who_exit',
        ),
    ]
