# Generated by Django 5.1.3 on 2025-12-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0050_remove_productobjectprocesslog_exit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessstart',
            name='quranteen_time_receive',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
