# Generated by Django 5.1.3 on 2025-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0051_productprocessstart_quranteen_time_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobject',
            name='full_sn',
            field=models.CharField(db_index=True, default='Blank', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
