# Generated by Django 5.1.3 on 2025-12-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0052_alter_productobject_full_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfrommistake',
            name='product_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.productobject'),
        ),
    ]
