# Generated by Django 5.1.3 on 2026-01-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0053_logfrommistake_product_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessstart',
            name='use_wider_create',
            field=models.BooleanField(default=False),
        ),
    ]
