# Generated by Django 5.1.3 on 2026-01-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0054_productprocessstart_use_wider_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productobject',
            options={'permissions': [('can_see_admin_page', 'Może oglądać admin page (API)')]},
        ),
    ]
