# Generated by Django 5.1.3 on 2026-01-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0055_alter_productobject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productobject',
            options={'permissions': [('can_see_admin_page', 'Może oglądać objekty w admin page (API)'), ('can_update_object_admin_page', 'Może modyfikować objekty w admin page (API)')]},
        ),
    ]
