# Generated by Django 5.1.3 on 2026-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0056_alter_productobject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocessstart',
            name='move_multi',
            field=models.BooleanField(default=False),
        ),
    ]
