# Generated by Django 5.1.3 on 2026-03-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0057_productprocessstart_move_multi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBasesSpiMapNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_base_name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('identyficator', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('line_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.placegrouptoappkill')),
                ('place_to_kill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.place')),
            ],
        ),
        migrations.CreateModel(
            name='LogFromSpiNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_id', models.IntegerField()),
                ('database', models.CharField(max_length=255)),
                ('pcb_name', models.CharField(max_length=255)),
                ('time_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=255)),
                ('machine_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.place')),
                ('product_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.productobject')),
            ],
            options={
                'indexes': [models.Index(fields=['-time_date'], name='checkproces_time_da_b059ce_idx'), models.Index(fields=['database'], name='checkproces_databas_0ba459_idx'), models.Index(fields=['result'], name='checkproces_result_053898_idx')],
                'constraints': [models.UniqueConstraint(fields=('database', 'fixed_id'), name='unique_fixed_id_to_database')],
            },
        ),
    ]
