# Generated by Django 5.1.3 on 2026-03-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0058_databasesspimapnew_logfromspinew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfromspinew',
            name='machine_name',
        ),
        migrations.AddField(
            model_name='logfromspinew',
            name='actual_database',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='logfromspinew',
            name='database',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
