# Generated by Django 5.1.3 on 2026-03-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0059_remove_logfromspinew_machine_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfromspinew',
            name='product_obj',
        ),
        migrations.AddField(
            model_name='logfromspinew',
            name='line_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkprocess.placegrouptoappkill'),
        ),
    ]
