# Generated by Django 5.1.3 on 2026-03-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0060_remove_logfromspinew_product_obj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logfromspinew',
            old_name='line_name',
            new_name='line',
        ),
    ]
