# Generated by Django 5.1.3 on 2026-03-30 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0061_rename_line_name_logfromspinew_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLogFromSpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.logfromspinew')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.place')),
                ('product_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkprocess.productobject')),
            ],
        ),
    ]
