# Generated by Django 5.1.3 on 2026-05-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0063_databasesspiasmmapnew'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logfromspinew',
            name='unique_fixed_id_to_database',
        ),
        migrations.AddConstraint(
            model_name='logfromspinew',
            constraint=models.UniqueConstraint(fields=('database', 'actual_database', 'fixed_id'), name='unique_fixed_id_per_db_and_month'),
        ),
    ]
