# Generated by Django 5.1.3 on 2026-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprocess', '0064_remove_logfromspinew_unique_fixed_id_to_database_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasesspiasmmapnew',
            name='place_to_kill',
        ),
        migrations.RemoveField(
            model_name='databasesspimapnew',
            name='place_to_kill',
        ),
        migrations.AddField(
            model_name='databasesspiasmmapnew',
            name='places_to_kill',
            field=models.ManyToManyField(blank=True, related_name='spi_asm_maps', to='checkprocess.place'),
        ),
        migrations.AddField(
            model_name='databasesspimapnew',
            name='places_to_kill',
            field=models.ManyToManyField(blank=True, related_name='spi_maps', to='checkprocess.place'),
        ),
    ]
